#!/usr/bin/env python3
"""
Turn a painted ground PNG back into a .jm, generating the tiles it needs.

Counterpart to map_export.py. You paint <name>_ground.png freely; this slices
it into 8x8 tiles, dedupes them, and emits:

  * a custom tile atlas PNG (the unique tiles, packed in a grid)
  * <Ground> XML entries, one per unique tile, in a free type-id range
  * a rewritten .jm whose ground layer points at those tiles

Objects (walls, portals, NPCs) are carried over from the source .jm untouched,
so painting never disturbs them. Only the ground layer is replaced.

Generated grounds are flat scenery: no blending, walkable, no sink. Ground has
no collision in this engine - collision comes from objects - so a painted wall
is decorative unless a real object is placed there.

  python dev/map_import.py source/Shared/resources/worlds/nexus.jm \
                           dev/mapart/nexus_ground.png --apply
"""

import argparse
import base64
import io
import json
import os
import struct
import sys
import zlib

try:
    from PIL import Image
except ImportError:
    sys.exit("Pillow missing.  python -m pip install Pillow")

TILE = 8
# Existing ground ids top out at 0xC004; start well clear of them.
BASE_TYPE = 0xD000
ATLAS_COLUMNS = 16

SET_NAME = "customMapTiles"
ATLAS_REL = os.path.join("client", "src", "kabam", "rotmg", "assets",
                         "custom", "images", "CustomMapTiles.png")
GROUND_XML_CLIENT = os.path.join("client", "src", "kabam", "rotmg", "assets",
                                 "prod", "xmls", "CustomMapGround.xml")
GROUND_XML_SERVER = os.path.join("source", "Shared", "resources", "xml",
                                 "custom", "CustomMapGround.xml")


def read_jm(path):
    d = json.load(io.open(path, encoding="utf-8"))
    w, h = d["width"], d["height"]
    idx = struct.unpack(">%dH" % (w * h), zlib.decompress(base64.b64decode(d["data"])))
    return d, w, h, list(idx)


def write_jm(path, d, w, h, idx):
    packed = struct.pack(">%dH" % (w * h), *idx)
    d["data"] = base64.b64encode(zlib.compress(packed, 9)).decode("ascii")
    io.open(path, "w", encoding="utf-8", newline="").write(
        json.dumps(d, separators=(",", ":")))


def slice_tiles(img, w, h):
    """(tile index per cell, list of unique 8x8 RGBA byte blobs)"""
    img = img.convert("RGBA")
    if img.size != (w * TILE, h * TILE):
        sys.exit(f"image is {img.size[0]}x{img.size[1]}, expected "
                 f"{w*TILE}x{h*TILE} ({w}x{h} tiles at {TILE}px)")
    px = img.load()
    uniq, order, cells = {}, [], []
    for ty in range(h):
        for tx in range(w):
            blob = bytes()
            rows = []
            for y in range(ty * TILE, ty * TILE + TILE):
                for x in range(tx * TILE, tx * TILE + TILE):
                    rows.extend(px[x, y])
            blob = bytes(rows)
            if blob not in uniq:
                uniq[blob] = len(order)
                order.append(blob)
            cells.append(uniq[blob])
    return cells, order


def build_atlas(tiles):
    cols = ATLAS_COLUMNS
    rows = (len(tiles) + cols - 1) // cols
    atlas = Image.new("RGBA", (cols * TILE, rows * TILE), (0, 0, 0, 0))
    for i, blob in enumerate(tiles):
        t = Image.frombytes("RGBA", (TILE, TILE), blob)
        atlas.paste(t, ((i % cols) * TILE, (i // cols) * TILE))
    return atlas


def ground_xml(count):
    out = ['<?xml version="1.0" encoding="ISO-8859-1"?>', "",
           "<!-- Generated by dev/map_import.py - do not hand edit.",
           "     One entry per unique painted tile. No BlendPriority so the",
           "     art renders exactly as drawn. -->",
           "<GroundTypes>"]
    for i in range(count):
        out += [f'   <Ground type="0x{BASE_TYPE + i:04x}" id="Painted {i}">',
                "      <Texture>",
                f"         <File>{SET_NAME}</File>",
                f"         <Index>{i}</Index>",
                "      </Texture>",
                "      <Speed>1.0</Speed>",
                "   </Ground>"]
    out += ["</GroundTypes>", ""]
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("jm")
    ap.add_argument("png")
    ap.add_argument("--root", default=".")
    ap.add_argument("--out", help="output .jm (default: overwrite source)")
    ap.add_argument("--apply", action="store_true",
                    help="write atlas + XML + .jm (otherwise dry run)")
    a = ap.parse_args()

    d, w, h, idx = read_jm(a.jm)
    cells, tiles = slice_tiles(Image.open(a.png), w, h)

    print(f"map           : {w}x{h} tiles ({w*TILE}x{h*TILE} px)")
    print(f"unique tiles  : {len(tiles)}  (of {w*h} cells)")
    print(f"ground ids    : 0x{BASE_TYPE:04x} - 0x{BASE_TYPE+len(tiles)-1:04x}")
    if BASE_TYPE + len(tiles) > 0xFFFF:
        sys.exit("too many unique tiles for the 16-bit ground id space")

    # rebuild the palette: keep each cell's objects, swap its ground
    old_dict = d["dict"]
    new_dict, keymap, new_idx = [], {}, []
    for cell_i, entry_idx in enumerate(idx):
        src = old_dict[entry_idx]
        objs = src.get("objs")
        regions = src.get("regions")
        ground_name = "Painted %d" % cells[cell_i]
        key = (ground_name, json.dumps(objs, sort_keys=True) if objs else None,
               json.dumps(regions, sort_keys=True) if regions else None)
        if key not in keymap:
            e = {"ground": ground_name}
            if objs:
                e["objs"] = objs
            if regions:
                e["regions"] = regions
            keymap[key] = len(new_dict)
            new_dict.append(e)
        new_idx.append(keymap[key])
    print(f"palette       : {len(old_dict)} -> {len(new_dict)} entries")

    kept = sum(1 for e in new_dict if e.get("objs"))
    print(f"object entries carried over: {kept}")

    if not a.apply:
        print("\ndry run - nothing written. re-run with --apply")
        return

    atlas = build_atlas(tiles)
    atlas_path = os.path.join(a.root, ATLAS_REL)
    os.makedirs(os.path.dirname(atlas_path), exist_ok=True)
    atlas.save(atlas_path)
    print("wrote", atlas_path, atlas.size)

    xml = ground_xml(len(tiles))
    for rel in (GROUND_XML_CLIENT, GROUND_XML_SERVER):
        p = os.path.join(a.root, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        io.open(p, "w", encoding="latin-1", newline="\n").write(xml)
        print("wrote", p)

    d["dict"] = new_dict
    out_jm = a.out or a.jm
    write_jm(out_jm, d, w, h, new_idx)
    print("wrote", out_jm)
    print("\nstill to wire up (one time):")
    print(f"  1. embed {os.path.basename(ATLAS_REL)} in EmbeddedAssets.as")
    print(f'  2. AssetLoader: addImageSet("{SET_NAME}", ..., {TILE}, {TILE})')
    print(f"  3. embed {os.path.basename(GROUND_XML_CLIENT)} in EmbeddedData.as")
    print("  4. copy the server XML into the world server's resources")


if __name__ == "__main__":
    main()
